// app/layout.tsx (修改後的程式碼 - 正確的)

import type { Metadata } from "next";
// import { GeistSans } from "geist/font/sans"; // <-- 1. 刪除或註解掉這行
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"> {/* <-- 2. 移除 className={GeistSans.className} */}
      <body>{children}</body>
    </html>
  );
}